name: Build and Run Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-run-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Debug build-args
      run: echo "Building with version 1.5.3"
    
    - name: Build iopaint-cpu
      uses: docker/build-push-action@v4
      with:
          push: true
          context: .
          file: ./docker/CPUDockerfile   # 指定 Dockerfile 路径
          tags: ricebug/iopaint-cpu:latest
          build-args: |
             version=1.5.3
    
    - name: Build iopaint-gpu
      uses: docker/build-push-action@v4
      with:
          push: true
          context: .
          file: ./docker/GPUDockerfile   # 指定 Dockerfile 路径
          tags: ricebug/iopaint-gpu:latest
          build-args: |
             version=1.5.3
